name: The White Ghost
favicon: null
layout_spectrum: 0.8371539826039225
typography_spectrum: 0.2967762325424701
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07853048760443926
  lightness: 0.9103061084169894
  saturation: 0.8164574285037816
  rhythmicContrast: 0.28168887039646506
purpose: []
